In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [3]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [4]:
df_tr=pd.read_csv('df__over_tr.csv',header=None)
df_ts=pd.read_csv('df__over_ts.csv',header=None)

In [5]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10172801, 12)
(2543201, 12)
(10172801,)
(2543201,)


#### Multi Layer Perceptron (Neural Network)

In [6]:
from sklearn.neural_network import MLPClassifier
nnc = MLPClassifier(activation='relu', learning_rate='adaptive', max_iter=1000, solver='adam').fit(X_train,y_train) 
y_tr_nnc_pred = nnc.predict(X_train)
y_ts_nnc_pred = nnc.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
nnc_cm_tr = confusion_matrix(y_train,y_tr_nnc_pred)
print(nnc_cm_tr)
accuracy_score(y_train, y_tr_nnc_pred)

[[3462220 1624645]
 [1062058 4023878]]


0.7358934869560507

In [8]:
nnc_cm_ts = confusion_matrix(y_test,y_ts_nnc_pred)
print(nnc_cm_ts)
accuracy_score(y_test, y_ts_nnc_pred)

[[ 864950  406186]
 [ 266003 1006062]]


0.7356917522445139

## Applying k-fold Cross Validation

In [8]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = nnc, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 73.22 %
Standard deviation: 0.48 %


In [9]:
accuracies

array([0.74084188, 0.73267832, 0.72657577, 0.72940341, 0.73138664])

## Grid Search

In [10]:
from sklearn.model_selection import GridSearchCV
parameters = [{'hidden_layer_sizes':[100,200,[100,100]],
               'activation':['identity','logistic','tanh','relu'],
               'solver': ['adam'], 
               'learning_rate':['constant','invscaling','adaptive'],
               'max_iter': [1000,2000]}]
grid_search = GridSearchCV(estimator = nnc, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

MemoryError: Unable to allocate 1.52 GiB for an array with shape (2034560, 100) and data type float64

## Metrics

In [9]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_nnc_pred))
print(jaccard_score(y_test,y_ts_nnc_pred))
print(f1_score(y_test,y_ts_nnc_pred))
print(precision_score(y_test,y_ts_nnc_pred))
print(recall_score(y_test,y_ts_nnc_pred))

0.7356715820638349
0.599470520202282
0.7495862069736279
0.7123833774237952
0.7908888303663728
