In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [2]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [3]:
df_tr=pd.read_csv('df__over_tr.csv',header=None)
df_ts=pd.read_csv('df__over_ts.csv',header=None)

In [4]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10172801, 12)
(2543201, 12)
(10172801,)
(2543201,)


#### SGD Classifier

In [5]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier(alpha=0.01, loss='log', penalty='none').fit(X_train,y_train)
y_tr_sgd_pred = sgd.predict(X_train)
y_ts_sgd_pred = sgd.predict(X_test)

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
sgd_cm_tr = confusion_matrix(y_train,y_tr_sgd_pred)
print(sgd_cm_tr)
accuracy_score(y_train, y_tr_sgd_pred)

[[3211010 1875855]
 [1776304 3309632]]


0.6409878655839233

In [7]:
sgd_cm_ts = confusion_matrix(y_test,y_ts_sgd_pred)
print(sgd_cm_ts)
accuracy_score(y_test, y_ts_sgd_pred)

[[803335 467801]
 [444392 827673]]


0.6413209180084468

## Applying k-fold Cross Validation

In [8]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = sgd, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 60.96 %
Standard deviation: 0.01 %


In [9]:
accuracies

array([0.60951576, 0.60950427, 0.6094905 , 0.60944332, 0.60981834])

## Grid Search

In [10]:
from sklearn.model_selection import GridSearchCV
parameters = [{"loss" : ["hinge", "log", "squared_hinge", "modified_huber"],
               "alpha" : [0.0001, 0.001, 0.01, 0.1], "penalty" : ["l2", "l1", "none"]}]
grid_search = GridSearchCV(estimator = sgd, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

Best accuracy: 64.10 %
Best parameters:  {'alpha': 0.01, 'loss': 'log', 'penalty': 'none'}


## Metrics

In [8]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_sgd_pred))
print(jaccard_score(y_test,y_ts_sgd_pred))
print(f1_score(y_test,y_ts_sgd_pred))
print(precision_score(y_test,y_ts_sgd_pred))
print(recall_score(y_test,y_ts_sgd_pred))

0.6413175078418581
0.4757107731285053
0.6447208786312497
0.6388958790373254
0.6506530719735234
