In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [2]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [3]:
df_tr=pd.read_csv('df__over_tr.csv',header=None)
df_tr[:2]

0         1         2         3         4         5         6   \
0  0.548129 -0.474781 -0.261172  0.582676 -0.998952  0.161931  0.005315   
1 -0.082416 -0.432479 -0.095805  0.612262 -0.799163 -0.783377 -0.087216   

         7         8         9         10        11   12  
0  0.015124  0.010220  0.004017  0.009899 -0.002410  0.0  
1 -0.092665 -0.090022 -0.147795 -0.246413  0.000853  0.0

In [4]:
df_ts=pd.read_csv('df__over_ts.csv',header=None)
df_ts[:2]

0         1         2         3         4         5         6   \
0 -0.866658 -0.071452 -0.750317  1.019449  0.287573 -0.222000 -0.079361   
1 -0.090683 -0.148418 -1.216780 -0.575059 -0.583747 -0.759693 -0.084742   

         7         8         9         10        11   12  
0 -0.129938 -0.102214 -0.132150 -0.226905 -0.064253  0.0  
1 -0.074892 -0.069629 -0.105506 -0.138969 -0.006599  1.0

In [5]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10172801, 12)
(2543201, 12)
(10172801,)
(2543201,)


## Classification algorithms

#### Decision Tree Classifier

In [6]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(max_depth=20, criterion='entropy').fit(X_train,y_train)
y_tr_dt_pred = dtc.predict(X_train)
y_ts_dt_pred = dtc.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
dt_cm_tr = confusion_matrix(y_train,y_tr_dt_pred)
print(dt_cm_tr)
accuracy_score(y_train, y_tr_dt_pred)

[[3852636 1234229]
 [1125045 3960891]]


0.7680801973812326

In [8]:
dt_cm_ts = confusion_matrix(y_test,y_ts_dt_pred)
print(dt_cm_ts)
accuracy_score(y_test, y_ts_dt_pred)

[[945133 326003]
 [302242 969823]]


0.7529707640096084

## Applying k-fold Cross Validation

In [9]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = dtc, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 72.17 %
Standard deviation: 0.06 %


In [10]:
accuracies

array([0.72287093, 0.72162482, 0.72136039, 0.72136088, 0.72152603])

## Grid Search

In [11]:
from sklearn.model_selection import GridSearchCV
parameters = [{'criterion':['gini', 'entropy'],'max_depth': list(range(1,21))}]
grid_search = GridSearchCV(estimator = dtc, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

Best accuracy: 75.14 %
Best parameters:  {'criterion': 'entropy', 'max_depth': 20}


## Metrics

In [9]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_dt_pred))
print(jaccard_score(y_test,y_ts_dt_pred))
print(f1_score(y_test,y_ts_dt_pred))
print(precision_score(y_test,y_ts_dt_pred))
print(recall_score(y_test,y_ts_dt_pred))

0.7529673181821934
0.6068721731490775
0.7553459239508219
0.748420698457972
0.7624005062634378
