In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [2]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [3]:
df_tr=pd.read_csv('df__over_tr.csv',header=None)
df_ts=pd.read_csv('df__over_ts.csv',header=None)

In [4]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10172801, 12)
(2543201, 12)
(10172801,)
(2543201,)


#### XGBoost Classifier

In [5]:
from xgboost import XGBClassifier
xgb = XGBClassifier(colsample_bytree=0.7, learning_rate=0.05, max_depth=8, min_child_weight=11, n_estimators=1000, objective='binary:logistic', subsample=0.8, tree_method='exact').fit(X_train,y_train)
y_tr_xgb_pred = xgb.predict(X_train)
y_ts_xgb_pred = xgb.predict(X_test)

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
xgb_cm_tr = confusion_matrix(y_train,y_tr_xgb_pred)
print(xgb_cm_tr)
accuracy_score(y_train, y_tr_xgb_pred)

[[3698999 1387866]
 [1200207 3885729]]


0.7455889484125365

In [7]:
xgb_cm_ts = confusion_matrix(y_test,y_ts_xgb_pred)
print(xgb_cm_ts)
accuracy_score(y_test, y_ts_xgb_pred)

[[922298 348838]
 [302629 969436]]


0.7438397515571911

## Applying k-fold Cross Validation

In [8]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = xgb, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 71.74 %
Standard deviation: 0.07 %


In [9]:
accuracies

array([0.7178728 , 0.71714277, 0.71857748, 0.71664881, 0.71673826])

## Grid Search

In [10]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators': [1000], #number of trees, change it to 1000 for better results
               'max_depth': [6,7,8],
               'learning_rate': [0.05], #so called `eta` value
               'objective':['binary:logistic'],
               'tree_method':['exact'],
               'min_child_weight': [11],
               'subsample': [0.8],
               'colsample_bytree': [0.7]}]
grid_search = GridSearchCV(estimator = xgb, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


## Metrics

In [8]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_xgb_pred))
print(jaccard_score(y_test,y_ts_xgb_pred))
print(f1_score(y_test,y_ts_xgb_pred))
print(precision_score(y_test,y_ts_xgb_pred))
print(recall_score(y_test,y_ts_xgb_pred))

0.7438330802365389
0.5980839075502976
0.7485012579434583
0.7353827808179483
0.7620962765267498
