In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [2]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [3]:
df_tr=pd.read_csv('df__under_tr.csv',header=None)
df_ts=pd.read_csv('df__under_ts.csv',header=None)

In [4]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(557088, 14)
(139272, 14)
(557088,)
(139272,)


#### Gaussian Naive Bayes classifier

In [5]:
from sklearn.naive_bayes import GaussianNB
nbc = GaussianNB(var_smoothing=1).fit(X_train,y_train)
y_tr_nb_pred = nbc.predict(X_train)
y_ts_nb_pred = nbc.predict(X_test)

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
nb_cm_tr = confusion_matrix(y_train,y_tr_nb_pred)
print(nb_cm_tr)
accuracy_score(y_train, y_tr_nb_pred)

[[176895 101927]
 [126737 151529]]


0.58953702108105

In [7]:
nb_cm_ts = confusion_matrix(y_test,y_ts_nb_pred)
print(nb_cm_ts)
accuracy_score(y_test, y_ts_nb_pred)

[[44159 25199]
 [31961 37953]]


0.5895801022459647

## Applying k-fold Cross Validation

In [8]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = nbc, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 55.15 %
Standard deviation: 0.17 %


In [9]:
accuracies

array([0.54904953, 0.55366278, 0.55030605, 0.55312924, 0.55155856])

## Grid Search

In [10]:
from sklearn.model_selection import GridSearchCV
parameters = [{'var_smoothing': [1e-12,1e-10,1e-7,1e-4,1e-3,1e-2,1e-1,1,10]}]
grid_search = GridSearchCV(estimator = nbc, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

Best accuracy: 58.96 %
Best parameters:  {'var_smoothing': 1}


## Metrics

In [8]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_nb_pred))
print(jaccard_score(y_test,y_ts_nb_pred))
print(f1_score(y_test,y_ts_nb_pred))
print(precision_score(y_test,y_ts_nb_pred))
print(recall_score(y_test,y_ts_nb_pred))

0.5897673947343396
0.3990306267282075
0.5704387296529542
0.6009785913351913
0.5428526475384043
