In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import mglearn
%matplotlib inline

In [2]:
import os
path = 'E:\Python Consumer Credit'
os.chdir(path)

In [3]:
df_tr=pd.read_csv('df__under_tr.csv',header=None)
df_ts=pd.read_csv('df__under_ts.csv',header=None)

In [4]:
X_train = df_tr.iloc[:,:-1].values
y_train = df_tr.iloc[:,-1].values
X_test = df_ts.iloc[:,:-1].values
y_test = df_ts.iloc[:,-1].values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(557088, 14)
(139272, 14)
(557088,)
(139272,)


#### SGD Classifier

In [7]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier(alpha= 0.1, loss='hinge', penalty='l2').fit(X_train,y_train)
y_tr_sgd_pred = sgd.predict(X_train)
y_ts_sgd_pred = sgd.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
sgd_cm_tr = confusion_matrix(y_train,y_tr_sgd_pred)
print(sgd_cm_tr)
accuracy_score(y_train, y_tr_sgd_pred)

[[141817 137005]
 [ 92881 185385]]


0.5873434717674766

In [9]:
sgd_cm_ts = confusion_matrix(y_test,y_ts_sgd_pred)
print(sgd_cm_ts)
accuracy_score(y_test, y_ts_sgd_pred)

[[35557 33801]
 [23439 46475]]


0.5890056867137687

## Applying k-fold Cross Validation

In [9]:
from sklearn.model_selection import KFold, cross_val_score
accuracies = cross_val_score(estimator = sgd, X = X_train, y = y_train, cv = 5)
print('Accuracy: {:.2f} %'.format(accuracies.mean()*100))
print('Standard deviation: {:.2f} %'.format(accuracies.std()*100))

Accuracy: 57.04 %
Standard deviation: 0.12 %


In [10]:
accuracies

array([0.56945915, 0.57129907, 0.57225942, 0.57004766, 0.5691591 ])

## Grid Search

In [11]:
from sklearn.model_selection import GridSearchCV
parameters = [{"loss" : ["hinge", "log", "squared_hinge", "modified_huber"],
               "alpha" : [0.0001, 0.001, 0.01, 0.1], "penalty" : ["l2", "l1", "none"]}]
grid_search = GridSearchCV(estimator = sgd, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best accuracy: {:.2f} %'.format(best_accuracy*100))
print('Best parameters: ',best_parameters)

Best accuracy: 58.72 %
Best parameters:  {'alpha': 0.1, 'loss': 'hinge', 'penalty': 'l2'}


## Metrics

In [10]:
from sklearn.metrics import roc_auc_score, jaccard_score, f1_score, precision_score, recall_score
print(roc_auc_score(y_test,y_ts_sgd_pred))
print(jaccard_score(y_test,y_ts_sgd_pred))
print(f1_score(y_test,y_ts_sgd_pred))
print(precision_score(y_test,y_ts_sgd_pred))
print(recall_score(y_test,y_ts_sgd_pred))

0.5887021081655759
0.4481029744974208
0.6188827485185432
0.5789401564602122
0.6647452584603942
